# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - cmdregistry

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://dregistrycm.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_fb0ad16644ae4cb38ba198863a0e13a2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cbcf832f4dbd409c912a446d2c49bff0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: dregistrycm.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fb0ad16644ae4cb38ba198863a0e13a2 }}/dcrimage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cmdregistry'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a2e65257a20d4c0f930a4cd2f3afcf7b }}
        images: 'dregistrycm.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fb0ad16644ae4cb38ba198863a0e13a2 }}/dcrimage:${{ github.sha }}'